spring:
    application:
        name: ncm
    profiles:
        include:
            - secret

notion:
    base-url: https://api.notion.com/v1
    version: 2022-06-28

logging:
    level:
        root: info
        io.usnack: debug